// // export const CountryCodes = [
// //     { code: "+93", name: "Afghanistan" },
// //     { code: "+355", name: "Albania" },
// //     { code: "+213", name: "Algeria" },
// //     { code: "+376", name: "Andorra" },
// //     { code: "+244", name: "Angola" },
// //     { code: "+1", name: "Antigua and Barbuda" },
// //     { code: "+54", name: "Argentina" },
// //     { code: "+374", name: "Armenia" },
// //     { code: "+61", name: "Australia" },
// //     { code: "+43", name: "Austria" },
// //     { code: "+994", name: "Azerbaijan" },
// //     { code: "+973", name: "Bahrain" },
// //     { code: "+880", name: "Bangladesh" },
// //     { code: "+1", name: "Barbados" },
// //     { code: "+32", name: "Belgium" },
// //     { code: "+501", name: "Belize" },
// //     { code: "+229", name: "Benin" },
// //     { code: "+975", name: "Bhutan" },
// //     { code: "+591", name: "Bolivia" },
// //     { code: "+387", name: "Bosnia and Herzegovina" },
// //     { code: "+267", name: "Botswana" },
// //     { code: "+55", name: "Brazil" },
// //     { code: "+673", name: "Brunei" },
// //     { code: "+359", name: "Bulgaria" },
// //     { code: "+226", name: "Burkina Faso" },
// //     { code: "+257", name: "Burundi" },
// //     { code: "+855", name: "Cambodia" },
// //     { code: "+237", name: "Cameroon" },
// //     { code: "+1", name: "Canada" },
// //     { code: "+238", name: "Cape Verde" },
// //     { code: "+236", name: "Central African Republic" },
// //     { code: "+235", name: "Chad" },
// //     { code: "+56", name: "Chile" },
// //     { code: "+86", name: "China" },
// //     { code: "+57", name: "Colombia" },
// //     { code: "+269", name: "Comoros" },
// //     { code: "+506", name: "Costa Rica" },
// //     { code: "+385", name: "Croatia" },
// //     { code: "+53", name: "Cuba" },
// //     { code: "+357", name: "Cyprus" },
// //     { code: "+420", name: "Czech Republic" },
// //     { code: "+243", name: "Democratic Republic of the Congo" },
// //     { code: "+45", name: "Denmark" },
// //     { code: "+253", name: "Djibouti" },
// //     { code: "+1", name: "Dominica" },
// //     { code: "+1", name: "Dominican Republic" },
// //     { code: "+593", name: "Ecuador" },
// //     { code: "+20", name: "Egypt" },
// //     { code: "+503", name: "El Salvador" },
// //     { code: "+240", name: "Equatorial Guinea" },
// //     { code: "+291", name: "Eritrea" },
// //     { code: "+372", name: "Estonia" },
// //     { code: "+268", name: "Eswatini" },
// //     { code: "+251", name: "Ethiopia" },
// //     { code: "+679", name: "Fiji" },
// //     { code: "+358", name: "Finland" },
// //     { code: "+33", name: "France" },
// //     { code: "+241", name: "Gabon" },
// //     { code: "+220", name: "Gambia" },
// //     { code: "+995", name: "Georgia" },
// //     { code: "+49", name: "Germany" },
// //     { code: "+233", name: "Ghana" },
// //     { code: "+30", name: "Greece" },
// //     { code: "+1", name: "Grenada" },
// //     { code: "+502", name: "Guatemala" },
// //     { code: "+224", name: "Guinea" },
// //     { code: "+245", name: "Guinea-Bissau" },
// //     { code: "+592", name: "Guyana" },
// //     { code: "+509", name: "Haiti" },
// //     { code: "+504", name: "Honduras" },
// //     { code: "+36", name: "Hungary" },
// //     { code: "+354", name: "Iceland" },
// //     { code: "+91", name: "India" },
// //     { code: "+62", name: "Indonesia" },
// //     { code: "+98", name: "Iran" },
// //     { code: "+964", name: "Iraq" },
// //     { code: "+353", name: "Ireland" },
// //     { code: "+972", name: "Israel" },
// //     { code: "+39", name: "Italy" },
// //     { code: "+225", name: "Ivory Coast" },
// //     { code: "+1", name: "Jamaica" },
// //     { code: "+81", name: "Japan" },
// //     { code: "+962", name: "Jordan" },
// //     { code: "+7", name: "Kazakhstan" },
// //     { code: "+254", name: "Kenya" },
// //     { code: "+686", name: "Kiribati" },
// //     { code: "+965", name: "Kuwait" },
// //     { code: "+996", name: "Kyrgyzstan" },
// //     { code: "+856", name: "Laos" },
// //     { code: "+371", name: "Latvia" },
// //     { code: "+961", name: "Lebanon" },
// //     { code: "+266", name: "Lesotho" },
// //     { code: "+231", name: "Liberia" },
// //     { code: "+218", name: "Libya" },
// //     { code: "+423", name: "Liechtenstein" },
// //     { code: "+370", name: "Lithuania" },
// //     { code: "+352", name: "Luxembourg" },
// //     { code: "+853", name: "Macau" },
// //     { code: "+389", name: "North Macedonia" },
// //     { code: "+261", name: "Madagascar" },
// //     { code: "+265", name: "Malawi" },
// //     { code: "+60", name: "Malaysia" },
// //     { code: "+960", name: "Maldives" },
// //     { code: "+223", name: "Mali" },
// //     { code: "+356", name: "Malta" },
// //     { code: "+692", name: "Marshall Islands" },
// //     { code: "+222", name: "Mauritania" },
// //     { code: "+230", name: "Mauritius" },
// //     { code: "+52", name: "Mexico" },
// //     { code: "+691", name: "Micronesia" },
// //     { code: "+373", name: "Moldova" },
// //     { code: "+377", name: "Monaco" },
// //     { code: "+976", name: "Mongolia" },
// //     { code: "+382", name: "Montenegro" },
// //     { code: "+212", name: "Morocco" },
// //     { code: "+258", name: "Mozambique" },
// //     { code: "+95", name: "Myanmar" },
// //     { code: "+264", name: "Namibia" },
// //     { code: "+674", name: "Nauru" },
// //     { code: "+977", name: "Nepal" },
// //     { code: "+31", name: "Netherlands" },
// //     { code: "+64", name: "New Zealand" },
// //     { code: "+505", name: "Nicaragua" },
// //     { code: "+227", name: "Niger" },
// //     { code: "+234", name: "Nigeria" },
// //     { code: "+47", name: "Norway" },
// //     { code: "+968", name: "Oman" },
// //     { code: "+92", name: "Pakistan" },
// //     { code: "+680", name: "Palau" },
// //     { code: "+970", name: "Palestine" },
// //     { code: "+507", name: "Panama" },
// //     { code: "+675", name: "Papua New Guinea" },
// //     { code: "+595", name: "Paraguay" },
// //     { code: "+51", name: "Peru" },
// //     { code: "+63", name: "Philippines" },
// //     { code: "+48", name: "Poland" },
// //     { code: "+351", name: "Portugal" },
// //     { code: "+974", name: "Qatar" },
// //     { code: "+242", name: "Republic of the Congo" },
// //     { code: "+40", name: "Romania" },
// //     { code: "+7", name: "Russia" },
// //     { code: "+250", name: "Rwanda" },
// //     { code: "+685", name: "Samoa" },
// //     { code: "+378", name: "San Marino" },
// //     { code: "+239", name: "Sao Tome and Principe" },
// //     { code: "+966", name: "Saudi Arabia" },
// //     { code: "+221", name: "Senegal" },
// //     { code: "+381", name: "Serbia" },
// //     { code: "+248", name: "Seychelles" },
// //     { code: "+232", name: "Sierra Leone" },
// //     { code: "+65", name: "Singapore" },
// //     { code: "+421", name: "Slovakia" },
// //     { code: "+386", name: "Slovenia" },
// //     { code: "+677", name: "Solomon Islands" },
// //     { code: "+252", name: "Somalia" },
// //     { code: "+27", name: "South Africa" },
// //     { code: "+82", name: "South Korea" },
// //     { code: "+211", name: "South Sudan" },
// //     { code: "+34", name: "Spain" },
// //     { code: "+94", name: "Sri Lanka" },
// //     { code: "+249", name: "Sudan" },
// //     { code: "+597", name: "Suriname" },
// //     { code: "+46", name: "Sweden" },
// //     { code: "+41", name: "Switzerland" },
// //     { code: "+963", name: "Syria" },
// //     { code: "+886", name: "Taiwan" },
// //     { code: "+992", name: "Tajikistan" },
// //     { code: "+255", name: "Tanzania" },
// //     { code: "+66", name: "Thailand" },
// //     { code: "+670", name: "Timor-Leste" },
// //     { code: "+228", name: "Togo" },
// //     { code: "+676", name: "Tonga" },
// //     { code: "+1", name: "Trinidad and Tobago" },
// //     { code: "+216", name: "Tunisia" },
// //     { code: "+90", name: "Turkey" },
// //     { code: "+993", name: "Turkmenistan" },
// //     { code: "+688", name: "Tuvalu" },
// //     { code: "+256", name: "Uganda" },
// //     { code: "+380", name: "Ukraine" },
// //     { code: "+971", name: "United Arab Emirates" },
// //     { code: "+44", name: "United Kingdom" },
// //     { code: "+1", name: "United States" },
// //     { code: "+598", name: "Uruguay" },
// //     { code: "+998", name: "Uzbekistan" },
// //     { code: "+678", name: "Vanuatu" },
// //     { code: "+58", name: "Venezuela" },
// //     { code: "+84", name: "Vietnam" },
// //     { code: "+967", name: "Yemen" },
// //     { code: "+260", name: "Zambia" },
// //     { code: "+263", name: "Zimbabwe" },
// //   ];

export const CountryCodes = [
  { code: "+93", name: "Afghanistan", length: 9, startsWith: "7" },
  { code: "+355", name: "Albania", length: 9, startsWith: "6" },
  { code: "+213", name: "Algeria", length: 9, startsWith: "5" },
  { code: "+376", name: "Andorra", length: 6, startsWith: "3" },
  { code: "+244", name: "Angola", length: 9, startsWith: "9" },
  { code: "+1", name: "Antigua and Barbuda", length: 10, startsWith: "268" },
  { code: "+54", name: "Argentina", length: 10, startsWith: "9" },
  { code: "+374", name: "Armenia", length: 8, startsWith: "9" },
  { code: "+61", name: "Australia", length: 9, startsWith: "4" },
  { code: "+43", name: "Austria", length: 10, startsWith: "6" },
  { code: "+994", name: "Azerbaijan", length: 9, startsWith: "5" },
  { code: "+973", name: "Bahrain", length: 8, startsWith: "3" },
  { code: "+880", name: "Bangladesh", length: 10, startsWith: "1" },
  { code: "+1", name: "Barbados", length: 10, startsWith: "246" },
  { code: "+32", name: "Belgium", length: 9, startsWith: "4" },
  { code: "+501", name: "Belize", length: 7, startsWith: "6" },
  { code: "+229", name: "Benin", length: 8, startsWith: "9" },
  { code: "+975", name: "Bhutan", length: 8, startsWith: "17" },
  { code: "+591", name: "Bolivia", length: 8, startsWith: "7" },
  { code: "+387", name: "Bosnia and Herzegovina", length: 8, startsWith: "6" },
  { code: "+267", name: "Botswana", length: 7, startsWith: "7" },
  { code: "+55", name: "Brazil", length: 11, startsWith: "11" },
  { code: "+673", name: "Brunei", length: 7, startsWith: "2" },
  { code: "+359", name: "Bulgaria", length: 9, startsWith: "8" },
  { code: "+226", name: "Burkina Faso", length: 8, startsWith: "7" },
  { code: "+257", name: "Burundi", length: 8, startsWith: "7" },
  { code: "+855", name: "Cambodia", length: 9, startsWith: "10" },
  { code: "+237", name: "Cameroon", length: 9, startsWith: "6" },
  { code: "+1", name: "Canada", length: 10, startsWith: "416" },
  { code: "+238", name: "Cape Verde", length: 7, startsWith: "2" },
  { code: "+236", name: "Central African Republic", length: 8, startsWith: "7" },
  { code: "+235", name: "Chad", length: 8, startsWith: "6" },
  { code: "+56", name: "Chile", length: 9, startsWith: "9" },
  { code: "+86", name: "China", length: 11, startsWith: "1" },
  { code: "+57", name: "Colombia", length: 10, startsWith: "3" },
  { code: "+269", name: "Comoros", length: 7, startsWith: "3" },
  { code: "+506", name: "Costa Rica", length: 8, startsWith: "2" },
  { code: "+385", name: "Croatia", length: 9, startsWith: "9" },
  { code: "+53", name: "Cuba", length: 8, startsWith: "5" },
  { code: "+357", name: "Cyprus", length: 8, startsWith: "9" },
  { code: "+420", name: "Czech Republic", length: 9, startsWith: "6" },
  { code: "+243", name: "Democratic Republic of the Congo", length: 9, startsWith: "8" },
  { code: "+45", name: "Denmark", length: 8, startsWith: "2" },
  { code: "+253", name: "Djibouti", length: 8, startsWith: "7" },
  { code: "+1", name: "Dominica", length: 10, startsWith: "767" },
  { code: "+1", name: "Dominican Republic", length: 10, startsWith: "809" },
  { code: "+593", name: "Ecuador", length: 9, startsWith: "2" },
  { code: "+20", name: "Egypt", length: 10, startsWith: "1" },
  { code: "+503", name: "El Salvador", length: 8, startsWith: "7" },
  { code: "+240", name: "Equatorial Guinea", length: 9, startsWith: "9" },
  { code: "+291", name: "Eritrea", length: 7, startsWith: "7" },
  { code: "+372", name: "Estonia", length: 7, startsWith: "5" },
  { code: "+268", name: "Eswatini", length: 7, startsWith: "7" },
  { code: "+251", name: "Ethiopia", length: 9, startsWith: "9" },
  { code: "+679", name: "Fiji", length: 7, startsWith: "9" },
  { code: "+358", name: "Finland", length: 10, startsWith: "4" },
  { code: "+33", name: "France", length: 9, startsWith: "6" },
  { code: "+241", name: "Gabon", length: 7, startsWith: "7" },
  { code: "+220", name: "Gambia", length: 7, startsWith: "7" },
  { code: "+995", name: "Georgia", length: 9, startsWith: "5" },
  { code: "+49", name: "Germany", length: 10, startsWith: "1" },
  { code: "+233", name: "Ghana", length: 9, startsWith: "2" },
  { code: "+30", name: "Greece", length: 10, startsWith: "2" },
  { code: "+1", name: "Grenada", length: 10, startsWith: "473" },
  { code: "+502", name: "Guatemala", length: 8, startsWith: "5" },
  { code: "+224", name: "Guinea", length: 8, startsWith: "6" },
  { code: "+245", name: "Guinea-Bissau", length: 7, startsWith: "7" },
  { code: "+592", name: "Guyana", length: 7, startsWith: "6" },
  { code: "+509", name: "Haiti", length: 8, startsWith: "3" },
  { code: "+504", name: "Honduras", length: 8, startsWith: "3" },
  { code: "+36", name: "Hungary", length: 9, startsWith: "20" },
   { code: "+354", name: "Iceland", length: 7, startsWith: "6" },
  { code: "+91", name: "India", length: 10, startsWith: "9" },
  { code: "+62", name: "Indonesia", length: 10, startsWith: "8" },
  { code: "+98", name: "Iran", length: 10, startsWith: "9" },
  { code: "+964", name: "Iraq", length: 10, startsWith: "7" },
  { code: "+353", name: "Ireland", length: 9, startsWith: "8" },
  { code: "+972", name: "Israel", length: 9, startsWith: "5" },
  { code: "+39", name: "Italy", length: 10, startsWith: "3" },
  { code: "+225", name: "Ivory Coast", length: 10, startsWith: "0" },
  { code: "+1", name: "Jamaica", length: 10, startsWith: "8" },
  { code: "+81", name: "Japan", length: 10, startsWith: "7" },
  { code: "+962", name: "Jordan", length: 9, startsWith: "7" },
  { code: "+7", name: "Kazakhstan", length: 10, startsWith: "7" },
  { code: "+254", name: "Kenya", length: 9, startsWith: "7" },
  { code: "+686", name: "Kiribati", length: 7, startsWith: "2" },
  { code: "+965", name: "Kuwait", length: 8, startsWith: "5" },
  { code: "+996", name: "Kyrgyzstan", length: 9, startsWith: "5" },
  { code: "+856", name: "Laos", length: 9, startsWith: "2" },
  { code: "+371", name: "Latvia", length: 8, startsWith: "2" },
  { code: "+961", name: "Lebanon", length: 8, startsWith: "3" },
  { code: "+266", name: "Lesotho", length: 8, startsWith: "5" },
  { code: "+231", name: "Liberia", length: 7, startsWith: "5" },
  { code: "+218", name: "Libya", length: 9, startsWith: "9" },
  { code: "+423", name: "Liechtenstein", length: 7, startsWith: "7" },
  { code: "+370", name: "Lithuania", length: 8, startsWith: "6" },
  { code: "+352", name: "Luxembourg", length: 8, startsWith: "6" },
  { code: "+853", name: "Macau", length: 8, startsWith: "6" },
  { code: "+389", name: "North Macedonia", length: 8, startsWith: "7" },
  { code: "+261", name: "Madagascar", length: 9, startsWith: "3" },
  { code: "+265", name: "Malawi", length: 9, startsWith: "8" },
  { code: "+60", name: "Malaysia", length: 9, startsWith: "1" },
  { code: "+960", name: "Maldives", length: 7, startsWith: "7" },
  { code: "+223", name: "Mali", length: 8, startsWith: "6" },
  { code: "+356", name: "Malta", length: 8, startsWith: "7" },
  { code: "+692", name: "Marshall Islands", length: 7, startsWith: "6" },
  { code: "+222", name: "Mauritania", length: 8, startsWith: "4" },
  { code: "+230", name: "Mauritius", length: 8, startsWith: "5" },
  { code: "+52", name: "Mexico", length: 10, startsWith: "1" },
  { code: "+691", name: "Micronesia", length: 7, startsWith: "2" },
  { code: "+373", name: "Moldova", length: 8, startsWith: "6" },
  { code: "+377", name: "Monaco", length: 8, startsWith: "6" },
  { code: "+976", name: "Mongolia", length: 8, startsWith: "8" },
  { code: "+382", name: "Montenegro", length: 8, startsWith: "6" },
  { code: "+212", name: "Morocco", length: 9, startsWith: "6" },
  { code: "+258", name: "Mozambique", length: 9, startsWith: "8" },
  { code: "+95", name: "Myanmar", length: 9, startsWith: "9" },
  { code: "+264", name: "Namibia", length: 9, startsWith: "8" },
  { code: "+674", name: "Nauru", length: 7, startsWith: "5" },
  { code: "+977", name: "Nepal", length: 10, startsWith: "9" },
  { code: "+31", name: "Netherlands", length: 9, startsWith: "6" },
  { code: "+64", name: "New Zealand", length: 9, startsWith: "2" },
  { code: "+505", name: "Nicaragua", length: 8, startsWith: "8" },
  { code: "+227", name: "Niger", length: 8, startsWith: "9" },
  { code: "+234", name: "Nigeria", length: 10, startsWith: "8" },
  { code: "+47", name: "Norway", length: 8, startsWith: "4" },
  { code: "+968", name: "Oman", length: 8, startsWith: "9" },
  { code: "+92", name: "Pakistan", length: 10, startsWith: "3" },
  { code: "+680", name: "Palau", length: 7, startsWith: "7" },
  { code: "+970", name: "Palestine", length: 9, startsWith: "5" },
  { code: "+507", name: "Panama", length: 8, startsWith: "6" },
  { code: "+675", name: "Papua New Guinea", length: 7, startsWith: "7" },
  { code: "+595", name: "Paraguay", length: 9, startsWith: "9" },
  { code: "+51", name: "Peru", length: 9, startsWith: "9" },
  { code: "+63", name: "Philippines", length: 10, startsWith: "9" },
  { code: "+48", name: "Poland", length: 9, startsWith: "5" },
  { code: "+351", name: "Portugal", length: 9, startsWith: "9" },
  { code: "+974", name: "Qatar", length: 8, startsWith: "3" },
  { code: "+242", name: "Republic of the Congo", length: 9, startsWith: "06" },
  { code: "+40", name: "Romania", length: 9, startsWith: "7" },
  { code: "+7", name: "Russia", length: 10, startsWith: "9" },
  { code: "+250", name: "Rwanda", length: 9, startsWith: "7" },
  { code: "+685", name: "Samoa", length: 7, startsWith: "7" },
  { code: "+378", name: "San Marino", length: 6, startsWith: "3" },
  { code: "+239", name: "Sao Tome and Principe", length: 7, startsWith: "9" },
  { code: "+966", name: "Saudi Arabia", length: 9, startsWith: "5" },
  { code: "+221", name: "Senegal", length: 9, startsWith: "7" },
  { code: "+381", name: "Serbia", length: 9, startsWith: "6" },
  { code: "+248", name: "Seychelles", length: 7, startsWith: "2" },
  { code: "+232", name: "Sierra Leone", length: 8, startsWith: "3" },
  { code: "+65", name: "Singapore", length: 8, startsWith: "8" },
  { code: "+421", name: "Slovakia", length: 9, startsWith: "9" },
  { code: "+386", name: "Slovenia", length: 8, startsWith: "3" },
  { code: "+677", name: "Solomon Islands", length: 7, startsWith: "7" },
  { code: "+252", name: "Somalia", length: 8, startsWith: "6" },
  { code: "+27", name: "South Africa", length: 9, startsWith: "6" },
  { code: "+82", name: "South Korea", length: 9, startsWith: "1" },
  { code: "+211", name: "South Sudan", length: 9, startsWith: "9" },
  { code: "+34", name: "Spain", length: 9, startsWith: "6" },
  { code: "+94", name: "Sri Lanka", length: 9, startsWith: "7" },
  { code: "+249", name: "Sudan", length: 9, startsWith: "9" },
  { code: "+597", name: "Suriname", length: 7, startsWith: "9" },
  { code: "+46", name: "Sweden", length: 9, startsWith: "7" },
  { code: "+41", name: "Switzerland", length: 9, startsWith: "7" },
   { code: "+963", name: "Syria", length: 9 , startsWith: "9"},
  { code: "+886", name: "Taiwan", length: 9, startsWith: "9" },
  { code: "+992", name: "Tajikistan", length: 9, startsWith: "9" },
  { code: "+255", name: "Tanzania", length: 9, startsWith: "7" },
  { code: "+66", name: "Thailand", length: 9, startsWith: "6" },
  { code: "+670", name: "Timor-Leste", length: 8, startsWith: "7" },
  { code: "+228", name: "Togo", length: 8, startsWith: "9" },
  { code: "+676", name: "Tonga", length: 7, startsWith: "7" },
  { code: "+1", name: "Trinidad and Tobago", length: 10, startsWith: "8" },
  { code: "+216", name: "Tunisia", length: 8, startsWith: "2" },
  { code: "+90", name: "Turkey", length: 10, startsWith: "5" },
  { code: "+993", name: "Turkmenistan", length: 8, startsWith: "6" },
  { code: "+688", name: "Tuvalu", length: 7, startsWith: "7" },
  { code: "+256", name: "Uganda", length: 9, startsWith: "7" },
  { code: "+380", name: "Ukraine", length: 9, startsWith: "6" },
  { code: "+971", name: "United Arab Emirates", length: 9, startsWith: "5"  },
  { code: "+44", name: "United Kingdom", length: 10, startsWith: "7" },
  { code: "+1", name: "United States", length: 10, startsWith: "2" },
  { code: "+598", name: "Uruguay", length: 9, startsWith: "9" },
  { code: "+998", name: "Uzbekistan", length: 9, startsWith: "9" },
  { code: "+678", name: "Vanuatu", length: 7, startsWith: "5" },
  { code: "+58", name: "Venezuela", length: 10, startsWith: "4" },
  { code: "+84", name: "Vietnam", length: 9, startsWith: "9" },
  { code: "+967", name: "Yemen", length: 9, startsWith: "7" },
  { code: "+260", name: "Zambia", length: 9, startsWith: "9" },
  { code: "+263", name: "Zimbabwe", length: 9, startsWith: "7" },
];

